#!/bin/sh

# remap the caps-lock key to an additional escape key 
xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'

# remap print screen to insert, to easily open Guake
# xmodmap -e "keycode 107 = Insert"

# use function keys as functions keys by default
/opt/logitech-k810/k810_conf -d /dev/hidraw* -f on
